# Site settings
title: A developer's blog
header-img: assets/img/pages/home/banner.jpg
description: "A blog about web technologies and collaborative work."
baseurl: ""
url: "http://blog.nicolas-brousse.fr"
twitter_username: nicolas_brousse
github_username:  nicolas-brousse
linkedin_username: nclbr

disqus_shortname: blog-nicolas-brousse
ga_id: UA-23920207-2

# Build settings
markdown: kramdown
highlighter: pygments
# permalink: pretty
permalink: /articles/:year-:month-:day-:title/
paginate: 10
paginate_path: /page/:num/

timezone: Europe/Paris

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

# safe: true
lsi: false

sass:
  sass_dir: assets/css/_sass
  style: :compressed

exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - Rakefile
  - TODO
  - CNAME
  - config.ru
  - tmp/
