# Site settings
title: A developer's blog
header-img: assets/img/home-bg.jpg
# email: hello@nicolas-brousse.fr
description: "A developer's blog"
baseurl: ""
url: "http://blog.nicolas-brousse.fr"
twitter_username: nicolas_brousse
github_username:  nicolas-brousse

# Build settings
markdown: kramdown
highlighter: pygments
# permalink: pretty
permalink: /articles/:year-:month-:day-:title
paginate: 10
paginate_path: /page/:num/

timezone: Europe/Paris

gems:
  # - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

safe: true
lsi: false

sass:
  sass_dir: assets/css/_sass
  style: :compressed

exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - Rakefile
  - TODO
  - CNAME
  - config.ru
